// <auto-generated />
using CleanServiceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanServiceApi.Migrations
{
    [DbContext(typeof(CleanServiceContext))]
    [Migration("20260129155441_InitSolicitud")]
    partial class InitSolicitud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanServiceApi.Models.Empleado", b =>
                {
                    b.Property<string>("EmailEmpleado")
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmailEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("CleanServiceApi.Models.Resenia", b =>
                {
                    b.Property<int>("IdResenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResenia"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdResenia");

                    b.HasIndex("EmailEmpleado");

                    b.HasIndex("EmailUsuario");

                    b.ToTable("Resenias");
                });

            modelBuilder.Entity("CleanServiceApi.Models.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int>("Disponibilidad")
                        .HasColumnType("integer");

                    b.Property<string>("EmailEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<double>("PrecioHora")
                        .HasColumnType("double precision");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("integer");

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("EmailEmpleado");

                    b.HasIndex("EmailUsuario");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("CleanServiceApi.Models.Usuario", b =>
                {
                    b.Property<string>("EmailUsuario")
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmailUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CleanServiceApi.Models.Resenia", b =>
                {
                    b.HasOne("CleanServiceApi.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmailEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanServiceApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("EmailUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CleanServiceApi.Models.Solicitud", b =>
                {
                    b.HasOne("CleanServiceApi.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmailEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanServiceApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("EmailUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
